### ISSUE TITLE
Error creating the forge object during XYZGrid spawn (map is also skewed).

### ISSUE THREAD

**Issue by Griatch** [InspectorCaracal/evennia-minimud#1]
## Problem

Running through the install instructions using latest Evennia 2.0.1 and a freshly cloned `evennia-minimud` repo, gives the following error on the `evennia xyzgrid spawn` step: 

```python
(.vienv3.11) $ evennia xyzgrid spawn
secret_settings.py file not found or failed to import.
This will (re)spawn the entire grid. If it was built before, it may spawn 
new rooms or delete rooms that no longer matches the grid.
Do you want to continue? [Y]/N? 
Beginner-Tutorial spawn ...
spawning/updating nodes for Z='townsburg' ...
  spawning room at xyz=(3, 1, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(6, 1, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(8, 1, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(11, 1, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(1, 2, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(6, 2, 'townsburg') (typeclasses.rooms.XYGridTrain)
  spawning room at xyz=(7, 2, 'townsburg') (typeclasses.rooms.XYGridRoom)
  spawning room at xyz=(8, 2, 'townsburg') (typeclasses.rooms.XYGridTrain)
  spawning room at xyz=(9, 2, 'townsburg') (typeclasses.rooms.XYZShopNTrain)
Traceback (most recent call last):
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/xymap_legend.py", line 317, in spawn
    nodeobj = NodeTypeclass.objects.get_xyz(xyz=xyz)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/xyzroom.py", line 111, in get_xyz
    raise self.model.DoesNotExist(inp)
evennia.contrib.grid.xyzgrid.xyzroom.XYZRoom.DoesNotExist: Query: xyz=(9,2,townsburg), 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/griatch/Devel/Home/evennia/.vienv3.11/bin/evennia", line 11, in <module>
    main()
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/server/evennia_launcher.py", line 2422, in main
    if run_custom_commands(option, *unknown_args):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/server/evennia_launcher.py", line 2026, in run_custom_commands
    command(*args)
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/launchcmd.py", line 446, in xyzcommand
    _option_spawn(*suboptions)
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/launchcmd.py", line 337, in _option_spawn
    grid.spawn(xyz=(x, y, z))
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/xyzgrid.py", line 272, in spawn
    xymap.spawn_nodes(xy=(x, y))
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/xymap.py", line 692, in spawn_nodes
    node.spawn()
  File "/home/griatch/Devel/Home/evennia/evennia/evennia/contrib/grid/xyzgrid/xymap_legend.py", line 330, in spawn
    raise RuntimeError(err)
RuntimeError: ["An error occurred while creating this 'A forge' object."]

```

## Some more analysis

The `MAP_STR` ('townsburg') in `world/starter_town.py` looks like this: 

```python
MAP_STR = r"""
+
  
5   o-----G-----G---R---R---o
    |      \    |           |
4   R     B-R $-R   $-B B   R
    |        \  |   |/  |   |
3   G-----R---#-#---R---R---G
    |          \    |   |   |
2   R         $-R-$ B   B   R
    |            \          |
1   o---R-----R---G-----R---o
  
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 
+
"""
```
(I added the x-grid coordinates to make it easier to see, can be a good idea to add this overall).  From this it would seem  `(9, 2, 'townsburg')` is the `$` symbol (a shop). 

This map string seems to be out of sync with what xyzgrid expects. It's possible it happens to work by chance in some circumstances, but this is the expected coordinate grid, with the standard x-grid also printed out (the + is not the origo, it's just marking the edge of the mapping area, including the axes): 

```python
MAP_STR = r"""
+ 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
  
4   o-----G-----G---R---R---o
    |      \    |           |
3   R     B-R $-R   $-B B   R
    |        \  |   |/  |   |
2   G-----R---#-#---R---R---G
    |          \    |   |   |
1   R         $-R-$ B   B   R
    |            \          |
0   o---R-----R---G-----R---o
  
+ 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
"""
```
Here `(9, 2, 'townsburg')` is an `R` (a road). I think this is what xyzgrid will actually see. 

Without diving deeper into the code and tracing it, I'm not sure why `(9,2)` causes an issue; the custom `(9.2)` prototype override sets this to be a typeclass `typeclasses.rooms.XYZShopNTrain` which does exist. I'd think that should replace the road typeclass set by default on this node. Not sure if there are other side effect due to the map being skewed though. Maybe the error actually happens on another node but the error reports the wrong coordinate due the skewed map? :shrug: 

Apart from the traceback happening, it's probably worth to correct the map since this is intended to act as something to build from ;)

**Comment by InspectorCaracal** [comment]
The problem appears to be unrelated to the map string; the room is failing to be created due to this issue https://github.com/evennia/evennia/issues/3240

**Comment by Griatch** [comment]
That other bug is resolved now, but the map string is nevertheless borked ;)

**Comment by InspectorCaracal** [comment]
> That other bug is resolved now, but the map string is nevertheless borked ;)

The map string still appears fine to me.

This is the string:
```
r"""
+
                               
5   o-----G-----G---R---R---o  
    |      \    |           |  
4   R     B-R $-R   $-B B   R  
    |        \  |   |/  |   |  
3   G-----R---#-#---R---R---G  
    |          \    |   |   |  
2   R         $-R-$ B   B   R  
    |            \          |  
1   o---R-----R---G-----R---o  
                               
0                              

+
"""
```

For an easily identifiable example, `6,3` and `7,3` should be the two `#` rooms, according to the prototyping. Putting the x coordinate numbers along the y value of 3 gives this:

```
r"""
+
                               
5   o-----G-----G---R---R---o  
    |      \    |           |  
4   R     B-R $-R   $-B B   R  
    |        \  |   |/  |   |  
3 0 1-2-3-4-5-6-7-8-9-0-1-2-3  
    |          \    |   |   |  
2   R         $-R-$ B   B   R  
    |            \          |  
1   o---R-----R---G-----R---o  
                               
0                              

+
"""
```

The 6 and 7 line up exactly with the `#` nodes, like they're supposed to.
